services:
  - type: web
    name: klyro-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot_server:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEB_APP_URL
        value: https://kobravania.github.io/klyro_app/
      - key: PORT
        value: 10000

